from typing import Protocol

from contracts import (
    ChatMessage,
    Decision,
    Meeting,
    Person,
    Report,
    TaskDraft,
    Team,
    TeamSettings,
    TranscriptSegment,
)
from contracts.meeting import MeetingStatus


class Store(Protocol):
    """Supabase Postgres. Every read is scoped to a team."""

    async def team_for_user(self, user_id: str) -> Team: ...
    async def members(self, team_id: str) -> list[Person]: ...
    async def settings(self, team_id: str) -> TeamSettings: ...
    async def save_settings(self, settings: TeamSettings) -> TeamSettings: ...

    async def create_meeting(self, team_id: str, title: str, host_id: str) -> Meeting: ...
    async def meeting(self, meeting_id: str) -> Meeting: ...
    async def meeting_by_code(self, code: str) -> Meeting: ...
    async def meetings(self, team_id: str) -> list[Meeting]: ...
    async def set_status(self, meeting_id: str, status: MeetingStatus) -> Meeting: ...

    async def add_segments(self, meeting_id: str, segments: list[TranscriptSegment]) -> None: ...
    async def transcript(self, meeting_id: str) -> list[TranscriptSegment]: ...
    async def add_public_chat(self, message: ChatMessage) -> None: ...

    async def save_report(self, report: Report) -> None: ...
    async def report(self, meeting_id: str) -> Report: ...
    async def update_task(self, task: TaskDraft) -> TaskDraft: ...
    async def decisions(self, team_id: str, query: str | None = None) -> list[Decision]: ...
    async def tasks(self, team_id: str, owner_id: str | None = None) -> list[TaskDraft]: ...
